### ISSUE TITLE
Fix config of cpp properties after rename

### ISSUE THREAD

**Issue by rydeom** [NessieCircuits/Riotee_AppTemplate#1]
With the changes of https://github.com/NessieCircuits/Riotee_AppTemplate/commit/25a0078d23e511689272d00de155478e9df55544 the config name changed from `sdkRoot` to `rioteeSdkRoot`. But in here https://github.com/NessieCircuits/Riotee_AppTemplate/blob/21d5edcc47b9c6dbebd8250289404360a211b0e4/.vscode/c_cpp_properties.json#L6-L12 its still `sdkRoot`. This needs to be changed to `rioteeSdkRoot`.

**Comment by geissdoerfer** [comment]
Sorry, somehow overlooked this issue.
